# # moex_list = [
#         # {'OZON': ["russia", "MOEX"]},
#         {'SBERP': 'ПАО Сбербанк (прив.)'},
#         {'MTSS': 'ПАО Мобильные ТелеСистемы'},
#         {'GAZP': 'ПАО Газпром'},
#         {'SIBN': 'ПАО Газпром нефть'},
#         {'TATN': 'ОАО Татнефть'},
#         {'VTBR': 'БАНК ВТБ'},
#         {'FIVE': 'X5 Retail Group'},
#         {'HYDR': 'ПАО "РусГидро"'},
#         {'SNGS': 'ПАО Сургутнефтегаз'},
#         # {'VKCO': 'VK Company Ltd DRC'},
#         {'ROSN': 'ПАО "Нефтяная компания "РОСНЕФТЬ"'},
#         {'PHOR': 'ОАО ФосАгро'},
#         {'LKOH': 'ПАО "Нефтяная компания "Лукойл"'},
#         {'GMKN': 'ПАО ГМК Норильский Никель'},
#         {'NLMK': 'ПАО Новолипецкий металлургический комбинат НЛМК'},
#         {'ALRS': 'ОАО АК АЛРОСА'},
#         {'YNDX': 'Яндекс Н.В.'},
#         {'SBER': 'ПАО Сбербанк'},
#         {'MGNT': 'ПАО МАГНИТ'},
#         {'PLZL': 'ПАО Полюс Золото'},
#         {'POLY': 'ОАО "Полиметалл"'},
#         # {'FEES': 'ПАО ФСК ЕЭС'},
#         {'MOEX': 'Московская биржа ОАО ММВБ'},
#         {'NVTK': 'ПАО "НОВАТЭК"'},
#         {'CHMF': 'ПАО "СЕВЕРСТАЛЬ"'}
#        ]

moex_list = {'OZON': ["russia", "MOEX"],
            'SBERP': ["russia", "MOEX"],
            'MTSS': ["russia", "MOEX"],
            'GAZP': ["russia", "MOEX"],
            'SIBN': ["russia", "MOEX"],
            'TATN': ["russia", "MOEX"],
            'VTBR': ["russia", "MOEX"],
            'FIVE': ["russia", "MOEX"],
            'HYDR': ["russia", "MOEX"],
            'SNGS': ["russia", "MOEX"],
            'VKCO': ["russia", "MOEX"],
            'ROSN': ["russia", "MOEX"],
            'PHOR': ["russia", "MOEX"],
            'LKOH': ["russia", "MOEX"],
            'GMKN': ["russia", "MOEX"],
            'NLMK': ["russia", "MOEX"],
            'ALRS': ["russia", "MOEX"],
            'YNDX': ["russia", "MOEX"],
            'SBER': ["russia", "MOEX"],
            'MGNT': ["russia", "MOEX"],
            'PLZL': ["russia", "MOEX"],
            'POLY': ["russia", "MOEX"],
            'FEES': ["russia", "MOEX"],
            'MOEX': ["russia", "MOEX"],
            'NVTK': ["russia", "MOEX"],
            'CHMF': ["russia", "MOEX"],
}